frontend:
    name: 'MSTFT'
    args:
        frame_size: 400
        frame_rate: 320
        num_mels  : 80

backbone:
    name: 'ResConv1d_BLSTM'
    args:
        out_channels: 256
        dropout     : 0.1