frontend:
    name: 'MSTFT'
    args:
        frame_size: 400
        frame_rate: 320
        num_mels  : 80

backbone:
    name: 'Conv2d_BGRU'
    args:
        channels: [32, 64, 128, 128, 128]
        dropout : 0.1