exp_path: 'exp'

train_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/HAD/HAD_train/train'
    data_list : '/work/hckuo145/SPADE/data/HAD/HAD_train/HAD_train_label.txt'
    frame_size: 400
    frame_rate: 320

valid_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/HAD/HAD_dev/dev'
    data_list : '/work/hckuo145/SPADE/data/HAD/HAD_dev/HAD_dev_label.txt'
    frame_size: 400
    frame_rate: 320

test_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/HAD/HAD_dev/dev'
    data_list : '/work/hckuo145/SPADE/data/HAD/HAD_dev/HAD_dev_label.txt'
    frame_size: 400
    frame_rate: 320

frame_loss:
    name: CrossEntropyLoss
    args: {'weight': !!python/object/apply:torch.tensor [[4.4964., 0.5625]]}

utter_loss:
    name: CrossEntropyLoss
    args: {}

optim:
    name: 'AdamW'
    args: {'lr': 0.001}

monitor:
    valid/frame_loss:
        mode: 'min'
    valid/utter_loss:
        mode: 'min'
    valid/loss:
        mode: 'min'
    valid/frame_A:
        mode: 'max'
    valid/frame_F1:
        mode: 'max'
    valid/utter_A:
        mode: 'max'
    valid/utter_F1:
        mode: 'max'
    valid/score:
        mode: 'max'
save_best_only: True

patience : 5
min_epoch: 50
max_epoch: -1