exp_path: 'exp'

train_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/combine'
    data_list : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/train_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

valid_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/combine'
    data_list : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/valid_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

test_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/combine'
    data_list : '/work/hckuo145/SPADE/data/SINE/medium-v3-unet-500k/test_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

frame_loss:
    name: CrossEntropyLoss
    args: {'weight': !!python/object/apply:torch.tensor [[15.9846, 0.5161]]}

utter_loss:
    name: CrossEntropyLoss
    args: {}

optim:
    name: 'AdamW'
    args: {'lr': 0.0001}

monitor:
    valid/frame_loss:
        mode: 'min'
    valid/utter_loss:
        mode: 'min'
    valid/loss:
        mode: 'min'
    valid/frame_A:
        mode: 'max'
    valid/frame_F1:
        mode: 'max'
    valid/utter_A:
        mode: 'max'
    valid/utter_F1:
        mode: 'max'
    valid/score:
        mode: 'max'
save_best_only: True

patience : 10
min_epoch: 100
max_epoch: -1