exp_path: 'exp'

train_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/combine'
    data_list : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/train_label_paste_real.txt'
    frame_size: 400
    frame_rate: 320

valid_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/combine'
    data_list : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/valid_label_paste_real.txt'
    frame_size: 400
    frame_rate: 320

test_dataset_args:
    data_path : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/combine'
    data_list : '/work/hckuo145/SPADE/data/Voicebox/medium-v3/test_label_paste_real.txt'
    frame_size: 400
    frame_rate: 320

frame_loss:
    name: CrossEntropyLoss
    args: {'weight': !!python/object/apply:torch.tensor [[14.1764, 0.5183]]}

dwsmp_loss:
    name: MultipleFrameLoss
    args: {}

isolt_loss:
    name: IsolatedFrameLoss
    args: {'max_neighbors': 3}

optim:
    name: 'AdamW'
    args: {'lr': 0.0001, 'weight_decay': 0.05}

monitor:
    valid/frame_loss:
        mode: 'min'
    valid/dwsmp_loss:
        mode: 'min'
    valid/isolt_loss:
        mode: 'min'
    valid/loss:
        mode: 'min'
    valid/frame_A:
        mode: 'max'
    valid/frame_F1:
        mode: 'max'
    valid/utter_A:
        mode: 'max'
    valid/utter_F1:
        mode: 'max'
    valid/score:
        mode: 'max'
save_best_only: True

patience : 10
min_epoch: 100
max_epoch: -1