exp_path: 'exp'

train_dataset_args:
    data_path : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/combine'
    data_list : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/train_2class_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

valid_dataset_args:
    data_path : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/combine'
    data_list : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/valid_2class_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

test_dataset_args:
    data_path : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/combine'
    data_list : '/home/hckuo/SPADE/data/VoiceNoNG/medium-v3-unet-500k/test_2class_edit_resyn.txt'
    frame_size: 400
    frame_rate: 320

frame_loss:
    name: CrossEntropyLoss
    args: {'weight': !!python/object/apply:torch.tensor [[15.1015, 0.5171]]}

utter_loss:
    name: CrossEntropyLoss
    args: {}

optim:
    name: 'AdamW'
    args: {'lr': 0.0001}

monitor:
    valid/frame_F1:
        mode: 'max'
    valid/utter_A:
        mode: 'max'
save_best_only: True

patience : 10
min_epoch: 100
max_epoch: -1
